#!/usr/bin/env python3
"""Compile declarative game policies to compact native constants.

Input paths are explicit so the compiler is shared by all games. Object bit
positions come from their catalogue, never from a scenario-specific enum.
"""
import argparse
import json
from pathlib import Path


def compile_rules(rules, keys):
    if rules.get("schema") != 1:
        raise ValueError("unsupported rules schema")
    if len(keys) != len(set(keys)):
        raise ValueError("duplicate object key")
    if len(keys) > 32:
        raise ValueError("object catalogue exceeds 32 bits")
    bits = {key: 1 << i for i, key in enumerate(keys)}
    trade = rules.get("trade", {"objects": [], "amulets": False, "limit": 0, "categories": "N"})
    if not isinstance(trade, dict):
        raise ValueError("trade must be an object")
    accepted = trade.get("objects")
    limit, amulets, categories = trade.get("limit"), trade.get("amulets"), trade.get("categories")
    if (not isinstance(accepted, list) or not all(isinstance(k, str) for k in accepted)
            or len(set(accepted)) != len(accepted) or any(k not in bits for k in accepted)):
        raise ValueError("trade requires distinct known object keys")
    if type(limit) is not int or not 0 <= limit <= 255 or type(amulets) is not bool:
        raise ValueError("trade requires a limit 0..255 and a boolean amulets flag")
    if (not isinstance(categories, str) or not 1 <= len(categories) <= 2
            or len(set(categories)) != len(categories) or any(k not in "NBM" for k in categories)):
        raise ValueError("native trade categories must contain one or two distinct N/B/M letters")
    trade_mask = sum(bits[k] for k in accepted)
    if trade_mask > 65535:
        raise ValueError("native trade backend currently requires 16-bit objects")
    groups = rules.get("save_migrations", [])
    compiled = []
    for group in groups:
        absent = group["when_none"]
        if not absent or len(absent) != len(set(absent)):
            raise ValueError("migration requires distinct guard flags")
        mask = sum(bits[key] for key in absent)
        if mask > 65535:
            raise ValueError("native migration backend currently requires 16-bit flags")
        rows = []
        for branch in group["first_visited"]:
            page, key = branch["page"], branch["give"]
            if type(page) is not int or not 0 <= page <= 65535:
                raise ValueError("invalid migration page")
            if key not in absent:
                raise ValueError("migration must set one of its guard flags")
            rows.append((mask, page, bits[key]))
        if not rows:
            raise ValueError("empty migration")
        compiled.extend(rows)
    if len(compiled) > 255:
        raise ValueError("too many migration branches")
    body = ", ".join("{%du, %du, %du}" % row for row in compiled) or "{0u, 0u, 0u}"
    return ("/* Generated by tools/compile_game_rules.py; edit the game RULES.json. */\n"
            "#ifndef GAME_RULES_H\n#define GAME_RULES_H\n"
            f"#define GAME_SAVE_MIGRATION_COUNT {len(compiled)}\n"
            f"#define GAME_SAVE_MIGRATIONS {{{body}}}\n"
            f"#define GAME_TRADE_OBJECT_MASK {trade_mask}u\n"
            f"#define GAME_TRADE_AMULETS {int(amulets)}\n"
            f"#define GAME_TRADE_LIMIT {limit}\n"
            f'#define GAME_TRADE_CATEGORIES "{categories}"\n'
            f"#define GAME_TRADE_CATEGORY_0 {ord(categories[0])}\n"
            f"#define GAME_TRADE_CATEGORY_1 {ord(categories[1]) if len(categories) > 1 else 0}\n"
            "#endif\n")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--rules", type=Path, required=True)
    parser.add_argument("--objects", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    keys = [line.split()[0] for line in args.objects.read_text().splitlines() if line.strip()]
    result = compile_rules(json.loads(args.rules.read_text()), keys)
    if not args.output.exists() or args.output.read_text() != result:
        args.output.write_text(result)


if __name__ == "__main__":
    main()
