/* Generated by tools/compile_game_rules.py; edit the game RULES.json. */
#ifndef GAME_RULES_H
#define GAME_RULES_H
#define GAME_SAVE_MIGRATION_COUNT 3
#define GAME_SAVE_MIGRATIONS {{28672u, 371u, 4096u}, {28672u, 173u, 8192u}, {28672u, 206u, 16384u}}
#define GAME_TRADE_OBJECT_MASK 396u
#define GAME_TRADE_AMULETS 1
#define GAME_TRADE_LIMIT 3
#define GAME_TRADE_CATEGORIES "N"
#define GAME_TRADE_CATEGORY_0 78
#define GAME_TRADE_CATEGORY_1 0
#endif
